### ISSUE TITLE
Add IUGA interaction

### ISSUE THREAD

**Issue by felipemfp** [GeoGuideProject/frontend#5]
### Briefing

The user should be able to ask for highlighting after the dataset has been processed.

### Tasks

- [x] Implement backend feature
- [ ] Add event to Highlight button in point profile
- [ ] Highlight similar points in the map
